name: CI

on:
  push:
    branches: 
      - master
      - v0.3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Test
      run: |
        julia --project -e 'using Pkg;  
                            Pkg.instantiate();
                            Pkg.build();
                            Pkg.test(;coverage=true);'
